config/routes.rb
Rails.application.routes.draw do
    resources :products

    root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params.require(:product).permit(:name, :description, :price))
    if @product.save
      redirect_to root_path, notice: "Product was created successfully"
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(params.require(:product).permit(:name, :description, :price))
      redirect_to root_path, notice: "Product was updated successfully"
    else
      render :edit
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, notice: "product was deleted"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrudPracticeProduct</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<h1> Edit Product Information </h1>
<%= form_for @product do |f| %>
<%= f.label :name %>
<%= f.text_area :name %>

<%= f.label :description %>
<%= f.text_area :description %>

<%= f.label :price %>
<%= f.number_field :price%>

<%= f.submit %>
<% end %>

app/views/products/index.html.erb
<div id="notice">
  <%= notice %>
</div>


<h1> Your Products Everywhere! </h1>

<%= link_to "New Products", new_product_path %>

<% @products.each do |product| %>
<table>
  <tr>
    <th>Name</th>
    <td><%= link_to "#{product.name}", product_path(product) %></td>

    <th>Description</th>
    <td><%= product.description %></td>

    <th>Price</th>
    <td><%= product.price %></td>

    <th>created</th>
    <td><%= product.created_at %></td>

    <th>updated</th>
    <td><%= product.updated_at %></td>

    <td><%= link_to "Edit", edit_product_path(product) %></td>
    <td><%= link_to "Show", product_path(product) %></td>
    <td><%= link_to "Delete", product_path(product), method: :delete, data: {confirm: "are you sure?"} %></td>
  </tr>
</table>
<% end %>

app/views/products/new.html.erb
    <h1> Product Factory </h1>
    <%= form_for @product do |f| %>
    <%= f.label :name %>
    <%= f.text_area :name %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.label :price %>
    <%= f.number_field :price%>

    <%= f.submit %>
    <% end %>

app/views/products/show.html.erb
<div id="notice">
  <%= notice %>
</div>

  <h1><%= @product.name %></h1>
    <%= @product.name %></br>
    <%= @product.description %></br>
    <%= @product.price %></br>
    <%= @product.created_at %></br>
    <%= @product.updated_at %></br>

    
    <%= link_to "Edit", edit_product_path(@product) %>
    <%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: "Are you sure?"} %>